name: dartmocks
version: 0.4.1
author: Victor Savkin <vic.savkin@gmail.com>
homepage: https://github.com/vsavkin/dartmocks
description: >
  A mock framework inspired by RSpec-Mocks.
dependencies:
  unittest: any