name: dartmocks
version: 0.5.0
author: Victor Savkin <vic.savkin@gmail.com>
homepage: https://github.com/vsavkin/dartmocks
description: >
  A mock framework inspired by RSpec-Mocks.
dependencies:
  unittest: ">= 0.8.7 <=1.0.0"
environment:
  sdk: ">=0.8.7 <2.0.0"